# data
DEAM_PATH = './data/DEAM'
PMEMO_PATH = './data/PMEmo/PMEmo2019'
COMBINED_PATH = './data/combined'
MODELS_PATH = './research/models/'

# dashboard
UPLOADED_AUDIO_PATH = './dashboard/UI/uploaded_audio'


## file names
# features
OPENSMILE_COMPARE2016_FEATURES_CSV = 'opensmile_compare2016_features.csv'
OPENSMILE_EMOBASE_FEATURES_CSV = 'opensmile_emobase_features.csv'
OPENSMILE_GEMAPS_FEATURES_CSV = 'opensmile_gemaps_features.csv'
OPENSMILE_EGEMAPS_FEATURES_CSV = 'opensmile_egemaps_features.csv'
ESSENTIA_FEATURES_CSV = 'essentia_features.csv'
ESSENTIA_FEATURES_FLATTENED_CSV = 'essentia_features_flattened.csv'
ESSENTIA_BEST_OVERALL_FEATURES_CSV = 'essentia_best_overall_features.csv'
ESSENTIA_BEST_VALENCE_FEATURES_CSV = 'essentia_best_valence_features.csv'
ESSENTIA_BEST_AROUSAL_FEATURES_CSV = 'essentia_best_arousal_features.csv'
ESSENTIA_ALL_OPENSMILE_COMPARE2016_FEATURES_CSV = 'essentia_all_opensmile_compare2016_features.csv'
ESSENTIA_ALL_OPENSMILE_EMOBASE_FEATURES_CSV = 'essentia_all_opensmile_emobase_features.csv'
ESSENTIA_ALL_OPENSMILE_GEMAPS_FEATURES_CSV = 'essentia_all_opensmile_gemaps_features.csv'
ESSENTIA_ALL_OPENSMILE_EGEMAPS_FEATURES_CSV = 'essentia_all_opensmile_egemaps_features.csv'
ESSENTIA_BEST_OVERALL_OPENSMILE_COMPARE2016_FEATURES_CSV = 'essentia_best_overall_opensmile_compare2016_features.csv'
ESSENTIA_BEST_OVERALL_OPENSMILE_EMOBASE_FEATURES_CSV = 'essentia_best_overall_opensmile_emobase_features.csv'
ESSENTIA_BEST_OVERALL_OPENSMILE_GEMAPS_FEATURES_CSV = 'essentia_best_overall_opensmile_gemaps_features.csv'
ESSENTIA_BEST_OVERALL_OPENSMILE_EGEMAPS_FEATURES_CSV = 'essentia_best_overall_opensmile_egemaps_features.csv'
ESSENTIA_BEST_VALENCE_OPENSMILE_GEMAPS_FEATURES_CSV = 'essentia_best_valence_opensmile_gemaps_features.csv'
ESSENTIA_BEST_VALENCE_OPENSMILE_EGEMAPS_FEATURES_CSV = 'essentia_best_valence_opensmile_egemaps_features.csv'
ESSENTIA_BEST_AROUSAL_OPENSMILE_GEMAPS_FEATURES_CSV = 'essentia_best_arousal_opensmile_gemaps_features.csv'
ESSENTIA_BEST_AROUSAL_OPENSMILE_EGEMAPS_FEATURES_CSV = 'essentia_best_arousal_opensmile_egemaps_features.csv'
STANDARDISED = 'standardised'
STANDARDISED_OPENSMILE_GEMAPS_FEATURES_CSV =  f'{STANDARDISED}_{OPENSMILE_GEMAPS_FEATURES_CSV}'
STANDARDISED_OPENSMILE_EGEMAPS_FEATURES_CSV =  f'{STANDARDISED}_{OPENSMILE_EGEMAPS_FEATURES_CSV}'
STANDARDISED_ESSENTIA_BEST_OVERALL_FEATURES_CSV = f'{STANDARDISED}_{ESSENTIA_BEST_OVERALL_FEATURES_CSV}'
STANDARDISED_ESSENTIA_BEST_VALENCE_FEATURES_CSV = f'{STANDARDISED}_{ESSENTIA_BEST_VALENCE_FEATURES_CSV}'
STANDARDISED_ESSENTIA_BEST_AROUSAL_FEATURES_CSV = f'{STANDARDISED}_{ESSENTIA_BEST_AROUSAL_FEATURES_CSV}'
STANDARDISED_ESSENTIA_ALL_OPENSMILE_COMPARE2016_FEATURES_CSV = f'{STANDARDISED}_{ESSENTIA_ALL_OPENSMILE_COMPARE2016_FEATURES_CSV}'
STANDARDISED_ESSENTIA_ALL_OPENSMILE_EMOBASE_FEATURES_CSV = f'{STANDARDISED}_{ESSENTIA_ALL_OPENSMILE_EMOBASE_FEATURES_CSV}'
STANDARDISED_ESSENTIA_ALL_OPENSMILE_GEMAPS_FEATURES_CSV = f'{STANDARDISED}_{ESSENTIA_ALL_OPENSMILE_GEMAPS_FEATURES_CSV}'
STANDARDISED_ESSENTIA_ALL_OPENSMILE_EGEMAPS_FEATURES_CSV = f'{STANDARDISED}_{ESSENTIA_ALL_OPENSMILE_EGEMAPS_FEATURES_CSV}'
STANDARDISED_ESSENTIA_BEST_OVERALL_OPENSMILE_COMPARE2016_FEATURES_CSV = f'{STANDARDISED}_{ESSENTIA_BEST_OVERALL_OPENSMILE_COMPARE2016_FEATURES_CSV}'
STANDARDISED_ESSENTIA_BEST_OVERALL_OPENSMILE_EMOBASE_FEATURES_CSV = f'{STANDARDISED}_{ESSENTIA_BEST_OVERALL_OPENSMILE_EMOBASE_FEATURES_CSV}'
STANDARDISED_ESSENTIA_BEST_OVERALL_OPENSMILE_GEMAPS_FEATURES_CSV = f'{STANDARDISED}_{ESSENTIA_BEST_OVERALL_OPENSMILE_GEMAPS_FEATURES_CSV}'
STANDARDISED_ESSENTIA_BEST_OVERALL_OPENSMILE_EGEMAPS_FEATURES_CSV = f'{STANDARDISED}_{ESSENTIA_BEST_OVERALL_OPENSMILE_EGEMAPS_FEATURES_CSV}'
STANDARDISED_ESSENTIA_BEST_VALENCE_OPENSMILE_GEMAPS_FEATURES_CSV = f'{STANDARDISED}_{ESSENTIA_BEST_VALENCE_OPENSMILE_GEMAPS_FEATURES_CSV}'
STANDARDISED_ESSENTIA_BEST_VALENCE_OPENSMILE_EGEMAPS_FEATURES_CSV = f'{STANDARDISED}_{ESSENTIA_BEST_VALENCE_OPENSMILE_EGEMAPS_FEATURES_CSV}'
STANDARDISED_ESSENTIA_BEST_AROUSAL_OPENSMILE_GEMAPS_FEATURES_CSV = f'{STANDARDISED}_{ESSENTIA_BEST_AROUSAL_OPENSMILE_GEMAPS_FEATURES_CSV}'
STANDARDISED_ESSENTIA_BEST_AROUSAL_OPENSMILE_EGEMAPS_FEATURES_CSV = f'{STANDARDISED}_{ESSENTIA_BEST_AROUSAL_OPENSMILE_EGEMAPS_FEATURES_CSV}'
NORMALISED = 'normalised'
NORMALISED_OPENSMILE_GEMAPS_FEATURES_CSV =  f'{NORMALISED}_{OPENSMILE_GEMAPS_FEATURES_CSV}'
NORMALISED_OPENSMILE_EGEMAPS_FEATURES_CSV =  f'{NORMALISED}_{OPENSMILE_EGEMAPS_FEATURES_CSV}'
NORMALISED_ESSENTIA_BEST_OVERALL_FEATURES_CSV = f'{NORMALISED}_{ESSENTIA_BEST_OVERALL_FEATURES_CSV}'
NORMALISED_ESSENTIA_BEST_VALENCE_FEATURES_CSV = f'{NORMALISED}_{ESSENTIA_BEST_VALENCE_FEATURES_CSV}'
NORMALISED_ESSENTIA_BEST_AROUSAL_FEATURES_CSV = f'{NORMALISED}_{ESSENTIA_BEST_AROUSAL_FEATURES_CSV}'
NORMALISED_ESSENTIA_ALL_OPENSMILE_COMPARE2016_FEATURES_CSV = f'{NORMALISED}_{ESSENTIA_ALL_OPENSMILE_COMPARE2016_FEATURES_CSV}'
NORMALISED_ESSENTIA_ALL_OPENSMILE_EMOBASE_FEATURES_CSV = f'{NORMALISED}_{ESSENTIA_ALL_OPENSMILE_EMOBASE_FEATURES_CSV}'
NORMALISED_ESSENTIA_ALL_OPENSMILE_GEMAPS_FEATURES_CSV = f'{NORMALISED}_{ESSENTIA_ALL_OPENSMILE_GEMAPS_FEATURES_CSV}'
NORMALISED_ESSENTIA_ALL_OPENSMILE_EGEMAPS_FEATURES_CSV = f'{NORMALISED}_{ESSENTIA_ALL_OPENSMILE_EGEMAPS_FEATURES_CSV}'
NORMALISED_ESSENTIA_BEST_OVERALL_OPENSMILE_COMPARE2016_FEATURES_CSV = f'{NORMALISED}_{ESSENTIA_BEST_OVERALL_OPENSMILE_COMPARE2016_FEATURES_CSV}'
NORMALISED_ESSENTIA_BEST_OVERALL_OPENSMILE_EMOBASE_FEATURES_CSV = f'{NORMALISED}_{ESSENTIA_BEST_OVERALL_OPENSMILE_EMOBASE_FEATURES_CSV}'
NORMALISED_ESSENTIA_BEST_OVERALL_OPENSMILE_GEMAPS_FEATURES_CSV = f'{NORMALISED}_{ESSENTIA_BEST_OVERALL_OPENSMILE_GEMAPS_FEATURES_CSV}'
NORMALISED_ESSENTIA_BEST_OVERALL_OPENSMILE_EGEMAPS_FEATURES_CSV = f'{NORMALISED}_{ESSENTIA_BEST_OVERALL_OPENSMILE_EGEMAPS_FEATURES_CSV}'
NORMALISED_ESSENTIA_BEST_VALENCE_OPENSMILE_GEMAPS_FEATURES_CSV = f'{NORMALISED}_{ESSENTIA_BEST_VALENCE_OPENSMILE_GEMAPS_FEATURES_CSV}'
NORMALISED_ESSENTIA_BEST_VALENCE_OPENSMILE_EGEMAPS_FEATURES_CSV = f'{NORMALISED}_{ESSENTIA_BEST_VALENCE_OPENSMILE_EGEMAPS_FEATURES_CSV}'
NORMALISED_ESSENTIA_BEST_AROUSAL_OPENSMILE_GEMAPS_FEATURES_CSV = f'{NORMALISED}_{ESSENTIA_BEST_AROUSAL_OPENSMILE_GEMAPS_FEATURES_CSV}'
NORMALISED_ESSENTIA_BEST_AROUSAL_OPENSMILE_EGEMAPS_FEATURES_CSV = f'{NORMALISED}_{ESSENTIA_BEST_AROUSAL_OPENSMILE_EGEMAPS_FEATURES_CSV}'



# annotations
DEAM_PROCESSED_STATIC_ANNOTATIONS_CSV = 'deam_static_annotations.csv'
PMEMO_PROCESSED_STATIC_ANNOTATIONS_CSV = 'pmemo_static_annotations.csv'

# model weights





# research/notebooks
SAMPLE_DEAM_AUDIO_PATH = '../../../data/DEAM/MEMD_audio/2.mp3'
SAMPLE_DEAM_SONG_FEATURE = '../../../data/DEAM/features/2.csv'
DEAM_AUDIO_FOLDER = '../../../data/DEAM/MEMD_audio'
DEAM_EXTRACTED_FEATURES_FOLDER = '../../../data/DEAM/processed/features'
DEAM_STATIC_ANNOTATIONS_CSV = '../../../data/DEAM/annotations/annotations averaged per song/song_level/static_annotations_averaged_songs_1_2000.csv'
DEAM_PROCESSED_ANNOTATIONS_FOLDER = '../../../data/DEAM/processed/annotations'

SAMPLE_PMEMO_AUDIO_PATH = '../../../data/PMEmo/PMEmo2019/chorus/5.mp3'
PMEMO_AUDIO_FOLDER = '../../../data/PMEmo/PMEmo2019/chorus'
PMEMO_EXTRACTED_FEATURES_FOLDER = '../../../data/PMEmo/PMEmo2019/processed/features'
PMEMO_STATIC_ANNOTATIONS_CSV = '../../../data/PMEmo/PMEmo2019/annotations/static_annotations.csv'
PMEMO_PROCESSED_ANNOTATIONS_FOLDER = '../../../data/PMEmo/PMEmo2019/processed/annotations'

COMBINED_EXTRACTED_FEATURES_FOLDER = '../../../data/combined/features'
COMBINED_STATIC_ANNOTATIONS_CSV = '../../../data/combined/annotations/combined_static_annotations.csv'
COMBINED_PROCESSED_ANNOTATIONS_FOLDER = '../../../data/combined/processed/annotations'